version: '3.3'
services:
  password-validator-client:
    container_name: password-validator-client
    build:
      context: ./password-validator-client
    ports:
      - "8080:8080"
    links: 
      - consul
    environment: 
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      MICRONAUT_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 8081
      GRPC_SERVER_HOST: password-validator-server
    depends_on: 
      - password-validator-server
      
  password-validator-server:
    container_name: password-validator-server
    build:
      context: ./password-validator-server
    ports:
      - "8081:8081"
    links: 
      - consul
    environment: 
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      GRPC_SERVER_PORT: 8081
      GRPC_SERVER_HOST: password-validator-server
    depends_on: 
      - consul
  
  consul:
    image: consul
    ports:
      - "8500:8500"

      
  